[options]
admin_passwd = admin
auth_admin_passkey_password = admin
db_host = localhost
db_name = project-odoo-sh
db_password = odoo
db_port = 5433
db_user = odoo
dbfilter = .*
http_interface = 127.0.0.1
http_port = 18000
log_level = info
xmlrpc_port = 18000
addons_path = /home/henrik/loym/gh/project-odoo-sh/loym-com/tools-odoo-sh/.tools-odoo-sh,
              /home/henrik/loym/gh/project-odoo-sh/odoo/design-themes/.design-themes,
              /home/henrik/loym/gh/project-odoo-sh/odoo/industry/.industry,
              /home/henrik/loym/gh/project-odoo-sh/odoo/odoo/.odoo
